apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-o40r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-o40r
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-o40r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-o40r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-o40r
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lgen-tenant/nodejs-users/simple-nodejs-app-o40r@sha256:4945ed0e88d6b8ed7e8906d564c81fdce41d1e67ad212a1f9f02ad2beaa9cd0e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
